config/routes.rb
Rails.application.routes.draw do
	root to: 'workouts#index'
	devise_for :users, skip: :registrations
	devise_scope :user do
		resource :registration,
		only: [:new, :create, :edit, :update, :destroy],
		path: 'users',
		path_names: { new: 'sign_up' },
		controller: 'users/registrations',
		as: :user_registration do
			get :cancel
		end
	end

	#Main Controllers
	resources :users
	resources :profiles
	resources :dashboard
	resources :workouts
    resources :exercises
    resources :activities

	#temporary while contructing pages.
	resources :not_implemented

resources :messages do
  member do
    post :new
  end
end
resources :conversations, only: [:index, :show, :new, :create] do
  member do
    post :reply
    post :trash
    post :untrash
    post :empty_trash
  end
 collection do
    get :trashbin
    get :empty_trash
 end
end

end

app/models/workout.rb
class Workout < ActiveRecord::Base
    has_many :activities, inverse_of: :workout, dependent: :destroy
    has_many :exercises, :through => :activities
    accepts_nested_attributes_for :activities,
      reject_if: proc { |a| a[:sets].blank?; },
      :allow_destroy => true

    belongs_to :user, inverse_of: :workouts

    validates_presence_of :title
    validates_presence_of :user

    validates_presence_of :activities
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.where(user_id: current_user.id)
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
    @workout.activities.new
  end

  # GET /workouts/1/edit
  def edit
    @workout = Workout.find(params[:id])
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)
    @workout.user_id = current_user.id if current_user

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    @workout = Workout.find(params[:id])
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    @workout.activities.destroy_all
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      #params[:workout].permit(:title, :description, :id,
                              #:user_id, :exercise_id,
                              #:activities_attributes => [:notes, :exercise_id, :sets, :reps, :weight, :duration])
      params[:workout].permit!
    end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
    def list_of_exercises_for_workout(exercises)
    output = ''
    exercises.each_with_index do |exercise,i|
      output += exercise.name
      output += ', ' unless i+1 == exercises.size   # don't add a comma to the last item
    end
    return output
  end

  def showExerciseTitle(exercise_id)
    exerciseName = Exercise.find(exercise_id).title
  end



end

app/views/workouts/_activity_fields.html.haml
.row.clearfix.fields.text-center
  .col-md-2{ :style => "overflow:hidden" }= f.collection_select :exercise_id, Exercise.all, :id, :title
  .col-md-3{ :style => "overflow:hidden" }= f.input :notes, label: false, :input_html => {:maxlength => 255, :size => 50, :style => "width:100%;height:75px"}
  .col-md-1{ :style => "overflow:hidden" }= f.input :reps, label: false, :input_html => {:maxlength => 3, :size => 3, :style => "width:45px"}
  .col-md-1{ :style => "overflow:hidden" }= f.input :sets, label: false, :input_html => {:maxlength => 3, :size => 3, :style => "width:45px"}
  .col-md-1{ :style => "overflow:hidden" }= f.input :weight, label: false, :input_html => {:maxlength => 3, :size => 3, :style => "width:45px"}
  .col-md-2= f.input :duration, label: false, :input_html => {:maxlength => 3, :size => 3, :style => "width:75px"}
  .col-md-2= activity_fields_removal_link(f)

app/views/workouts/_form.html.haml
= simple_form_for(@workout, html: {class: 'form-inline' }) do |f|
  = f.error_notification
  .form-inputs
    = f.input :title
    = f.input :description
  .form-actions
    = f.button :submit

app/views/workouts/edit.html.haml
%h2 Editing workout
%hr{:style => "border:3px solid black"}/
= simple_form_for(@workout, html: {class: 'form-inline edit_workout' }) do |f|
  = f.error_notification
  .form-horizontal
    = f.input :title
    = f.input :description
  %h4 Activities in this workout:
  .row.clearfix.text-center
    .col-md-2 Title
    .col-md-3 Notes
    .col-md-1 Reps
    .col-md-1 Sets
    .col-md-1 Weight
    .col-md-2 Duration
    .col-md-2 Actions

  = f.simple_fields_for :activities, f.object.activities.order(:id) do |builder|
    = render 'activity_fields', f: builder
  %p
  .row.clearfix
    .col-md-6
      = link_to_add_fields('Add Activity', f, :activities)
    .col-md-6.text-right
      = f.button :submit, class: 'btn btn-success'
      %p
      = link_to 'Show', @workout
      |
      =link_to 'Back', workouts_path

app/views/workouts/index.html.haml
%h1 Listing workouts
%table.table.table-striped
  %thead
    %tr
      %th Created
      %th Title
      %th Description
      %th Actions
  %tbody
    - @workouts.each do |workout|
      %tr
        %td= format_datetime(workout.created_at,:short)
        %td= workout.title
        %td= workout.description
        %td
          = link_to 'Show', workout
          |
          \#{link_to 'Edit', edit_workout_path(workout)}
          |
          \#{link_to 'Remove', workout, method: :delete, data: { confirm: 'Are you sure?' }}
%br/
= link_to 'New Workout', new_workout_path, class: 'btn btn-success'

app/views/workouts/new.html.haml
%h2 New workout
%hr.thickRule
= simple_form_for(@workout, html: {class: 'row.clearfix' }) do |f|
  .col-md-12
    = f.error_notification
  .row.clearfix
    .col-md-6
      = f.input :title, :input_html => {:maxlength => 255, :size => 50, :style => ""}
    .col-md-6
      = f.input :description, :input_html => {:maxlength => 255, :size => 50, :style => "width:100%;height:75px"}
  .row.clearfix.top-spacing
    %h4.col-md-12 Activities in this workout:
  .row.clearfix.text-center.top-spacing
    .col-md-2 Title
    .col-md-3 Notes
    .col-md-1 Reps
    .col-md-1 Sets
    .col-md-1 Weight
    .col-md-2 Duration
    .col-md-2 Actions

  = f.simple_fields_for :activities do |builder|
    = render 'activity_fields', f: builder
  %p
  .row.clearfix
    .col-md-6
      = link_to_add_fields('Add Activity', f, :activities)
    .col-md-6.text-right
      = f.button :submit, class: 'btn btn-success'
      %p
      = link_to 'Back', workouts_path, class: 'btn btn-danger'

app/views/workouts/show.html.haml
.row.clearfix
  .col-md-3
    %h4 Workout Name:
    = @workout.title
  .col-md-3
    %h4 Workout Description:
    = @workout.description
.row.clearfix.top-spacing
  .col-md-12.text-left
    %h4 Activities in this Workout:
    %hr
%h4.row.clearfix.text-center
  .col-md-2 Title
  .col-md-3 Notes
  .col-md-1 Reps
  .col-md-1 Sets
  .col-md-1 Weight
  .col-md-2 Duration
- @workout.activities.each do |a|
  .row.clearfix.text-center
    .col-md-2
      = showExerciseTitle(a.exercise_id)
    .col-md-3
      = a.notes
    .col-md-1
      = a.sets
    .col-md-1
      = a.reps
    .col-md-1
      = a.weight
    .col-md-2
      = a.duration
%hr.thickRule
.row-clearfix.text-right.top-spacing
  %h4
    = link_to 'Edit', edit_workout_path(@workout)
    |
    \#{link_to 'Back', workouts_path}