config/routes.rb
Rails.application.routes.draw do
	root to: 'workouts#index'
	devise_for :users, skip: :registrations
	devise_scope :user do
		resource :registration,
		only: [:new, :create, :edit, :update, :destroy],
		path: 'users',
		path_names: { new: 'sign_up' },
		controller: 'users/registrations',
		as: :user_registration do
			get :cancel
		end
	end

	#Main Controllers
	resources :users
	resources :profiles
	resources :dashboard
	resources :workouts
    resources :exercises
    resources :activities

	#temporary while contructing pages.
	resources :not_implemented

resources :messages do
  member do
    post :new
  end
end
resources :conversations, only: [:index, :show, :new, :create] do
  member do
    post :reply
    post :trash
    post :untrash
    post :empty_trash
  end
 collection do
    get :trashbin
    get :empty_trash
 end
end

end

app/models/mailboxer/conversation.rb
class Mailboxer::Conversation < ActiveRecord::Base
  self.table_name = :mailboxer_conversations

  attr_accessible :subject if Mailboxer.protected_attributes?

  has_many :opt_outs, :dependent => :destroy, :class_name => "Mailboxer::Conversation::OptOut"
  has_many :messages, :dependent => :destroy, :class_name => "Mailboxer::Message"
  has_many :receipts, :through => :messages,  :class_name => "Mailboxer::Receipt"

  validates :subject, :presence => true,
                      :length => { :maximum => Mailboxer.subject_max_length }

  before_validation :clean

  scope :participant, lambda {|participant|
    where('mailboxer_notifications.type'=> Mailboxer::Message.name).
    order("mailboxer_conversations.updated_at DESC").
    joins(:receipts).merge(Mailboxer::Receipt.recipient(participant)).uniq
  }
  scope :inbox, lambda {|participant|
    participant(participant).merge(Mailboxer::Receipt.inbox.not_trash.not_deleted)
  }
  scope :sentbox, lambda {|participant|
    participant(participant).merge(Mailboxer::Receipt.sentbox.not_trash.not_deleted)
  }
  scope :trash, lambda {|participant|
    participant(participant).merge(Mailboxer::Receipt.trash)
  }
  scope :unread,  lambda {|participant|
    participant(participant).merge(Mailboxer::Receipt.is_unread)
  }
  scope :not_trash,  lambda {|participant|
    participant(participant).merge(Mailboxer::Receipt.not_trash)
  }

  #Mark the conversation as read for one of the participants
  def mark_as_read(participant)
    return unless participant
    receipts_for(participant).mark_as_read
  end

  #Mark the conversation as unread for one of the participants
  def mark_as_unread(participant)
    return unless participant
    receipts_for(participant).mark_as_unread
  end

  #Move the conversation to the trash for one of the participants
  def move_to_trash(participant)
    return unless participant
    receipts_for(participant).move_to_trash
  end

  #Takes the conversation out of the trash for one of the participants
  def untrash(participant)
    return unless participant
    receipts_for(participant).untrash
  end

  #Mark the conversation as deleted for one of the participants
  def mark_as_deleted(participant)
    return unless participant
    deleted_receipts = receipts_for(participant).mark_as_deleted
    if is_orphaned?
      destroy
    else
      deleted_receipts
    end
  end

  #Returns an array of participants
  def recipients
    return [] unless original_message
    Array original_message.recipients
  end

  #Returns an array of participants
  def participants
    recipients
  end

  #Originator of the conversation.
  def originator
    @originator ||= original_message.sender
  end

  #First message of the conversation.
  def original_message
    @original_message ||= messages.order('created_at').first
  end

  #Sender of the last message.
  def last_sender
    @last_sender ||= last_message.sender
  end

  #Last message in the conversation.
  def last_message
    @last_message ||= messages.order('created_at DESC').first
  end

  #Returns the receipts of the conversation for one participants
  def receipts_for(participant)
    Mailboxer::Receipt.conversation(self).recipient(participant)
  end

  #Returns the number of messages of the conversation
  def count_messages
    Mailboxer::Message.conversation(self).count
  end

  #Returns true if the messageable is a participant of the conversation
  def is_participant?(participant)
    return false unless participant
    receipts_for(participant).any?
  end

    #Adds a new participant to the conversation
    def add_participant(participant)
        messages.each do |message|
      Mailboxer::ReceiptBuilder.new({
        :notification => message,
        :receiver     => participant,
        :updated_at   => message.updated_at,
        :created_at   => message.created_at
      }).build.save
        end
    end

  #Returns true if the participant has at least one trashed message of the conversation
  def is_trashed?(participant)
    return false unless participant
    receipts_for(participant).trash.count != 0
  end

  #Returns true if the participant has deleted the conversation
  def is_deleted?(participant)
    return false unless participant
    return receipts_for(participant).deleted.count == receipts_for(participant).count
  end

  #Returns true if both participants have deleted the conversation
  def is_orphaned?
    participants.reduce(true) do |is_orphaned, participant|
      is_orphaned && is_deleted?(participant)
    end
  end

  #Returns true if the participant has trashed all the messages of the conversation
  def is_completely_trashed?(participant)
    return false unless participant
    receipts_for(participant).trash.count == receipts_for(participant).count
  end

  def is_read?(participant)
    !is_unread?(participant)
  end

  #Returns true if the participant has at least one unread message of the conversation
  def is_unread?(participant)
    return false unless participant
    receipts_for(participant).not_trash.is_unread.count != 0
  end

  # Creates a opt out object
  # because by default all particpants are opt in
  def opt_out(participant)
    return unless has_subscriber?(participant)
    opt_outs.create(:unsubscriber => participant)
  end

  # Destroys opt out object if any
  # a participant outside of the discussion is, yet, not meant to optin
  def opt_in(participant)
    opt_outs.unsubscriber(participant).destroy_all
  end

  # tells if participant is opt in
  def has_subscriber?(participant)
    !opt_outs.unsubscriber(participant).any?
  end

  def body
  end

  protected

  #Use the default sanitize to clean the conversation subject
  def clean
    self.subject = sanitize subject
  end

  def sanitize(text)
    ::Mailboxer::Cleaner.instance.sanitize(text)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  #before_filter :mailbox, :get_box
  before_filter :get_mailbox, :get_box
  #helper_method :mailbox, :conversation
  #before_filter :check_current_subject_in_conversation, :only => [:show, :update, :destroy]
  require 'pry'

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox.page(params[:page]).per(9)
    elsif @box.eql? "sentbox"
      @conversations = @mailbox.sentbox.page(params[:page]).per(9)
    else
      @conversations ||= @mailbox.trash.page(params[:page]).per(9)
    end

    respond_to do |format|
      format.html { render @conversations if request.xhr? }
    end
  end

  def show
    if @box.eql? 'trash'
      @receipts = @mailbox.receipts_for(conversation).trash
    else
      @receipts = @mailbox.receipts_for(conversation).not_trash
    end
    @receipts.mark_as_read
  end

  def create
    recipient_emails = conversation_params(:recipients).split(',')
    recipients = User.where(email: recipient_emails).all

    conversation = current_user.send_message(recipients, *conversation_params(:body, :subject)).conversation

    redirect_to conversation
  end

  def reply
    current_user.reply_to_conversation(conversation, *conversation_params(:body))
    redirect_to conversation_path
  end

  def trashbin
    @trash ||= current_user.mailbox.trash.all
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to :conversations
  end

  def empty_trash
    current_user.mark_as_deleted(mailbox.trash.to_a)
    redirect_to root
  end

  private

  def get_mailbox
   @mailbox ||= current_user.mailbox
  end

  def conversation
   @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def get_box
    if params[:box].blank? or !["inbox","sentbox","trash"].include?params[:box]
      params[:box] = 'inbox'
    end

    @box = params[:box]
  end

  def check_current_subject_in_conversation
    @conversation = Conversation.find_by_id(params[:id])

    if @conversation.nil? or !@conversation.is_participant?(@actor)
      redirect_to conversations_path(:box => @box)
    return
    end
  end

  def conversation_params(*keys)
   fetch_params(:conversation, *keys)
  end

  def message_params(*keys)
   fetch_params(:message, *keys)
  end

  def fetch_params(key, *subkeys)
   params[key].instance_eval do
     case subkeys.size
     when 0 then self
     when 1 then self[subkeys.first]
     else subkeys.map{|k| self[k] }
     end
   end
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversations_layout.html.haml
.row
  .col-md-4
    %strong Sent
  .col-md-5
    %strong Subject
  .col-md-1
    %strong Actions
- @box.each do |conversation|
  .row.wt-row
    .col-md-4= format_datetime(conversation.updated_at, :short)
    .col-md-5= link_to conversation.subject, conversation_path(conversation.id)
    .col-md-1= link_to '', {:controller => "conversations", :action => "trash", :id => conversation.id}, :title=> "Move to Trash", :method=>'post', :class => 'fa fa-trash-o'

app/views/conversations/_form.html.haml
= simple_form_for :messages, url: :conversations do |f|
  = f.input :recipients
  = f.input :subject
  = f.input :body
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = submit_tag 'Cancel', type: :reset, class: 'btn btn-danger'

app/views/conversations/_reply.html.haml
= simple_form_for :conversation, url: :conversations do |f|
  = f.input :recipients
  = f.input :subject
  = f.input :body
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = submit_tag 'Cancel', type: :reset, class: 'btn btn-danger'

app/views/conversations/index.html.haml
%h3 My Messages
.row.wt-row
  .col-md-2.wt-mailbox-links
    - if params[:box] == 'sentbox'
      - @box = @mailbox.sentbox
    - elsif params[:box] == 'trash'
      - @box = @mailbox.trash
    - else
      - @box = @mailbox.inbox
    = links = ['inbox', 'sentbox', 'trash'].map { |li| link_to li, "?box=" + li }.join(' <p></p>').html_safe
  .col-md-10
    = render 'conversations_layout', object: @box, locals: {boxname: @boxname}
.row
  .col-md-3
    = button_to messages_path, method: :get, class: 'btn btn-success pull-left' do
      %span.fa.fa-envelope-o
        New Message
  .col-md-9
    - if params[:box] == 'trash'
      = button_to empty_trash_conversations_path, class: 'btn btn-danger', data: { confirm: "Are you sure?" } do
        %span.fa.fa-trash-o
          Empty Trash

app/views/conversations/show.html.haml
.row-clearfix
  %h3
    %strong Subject:
    = @conversation.subject
.row-clearfix
  - @receipts.reverse.each do |receipt|
    .row.wt-row
      .col-md-6
        .col-md-6
          = image_tag get_sender_picture_url(receipt.message.sender.id), alt: "Profile Pic", class: 'wt-profile-icon'
        .col-md-6
          %strong From:
          = receipt.message.sender.name
          %br
          %strong Sent:
          = format_datetime(receipt.message.updated_at, :short)
      .col-md-6
        %strong Message:
        %br
        = receipt.message.body
.row-clearfix
  %h4.text-bold Reply:
  =simple_form_for :conversation, :url => url_for(:action => 'reply', :controller => 'conversations' ) do |f|
    = f.input :body, :as => 'text', label: false, :input_html => {:rows => 10, :cols => '50%', :class => 'col-md-9' }
    .text-center= f.button :submit, "Reply", class: 'btn btn-primary'