config/routes.rb
Rails.application.routes.draw do
	root to: 'workouts#index'
	devise_for :users, skip: :registrations
	devise_scope :user do
		resource :registration,
		only: [:new, :create, :edit, :update, :destroy],
		path: 'users',
		path_names: { new: 'sign_up' },
		controller: 'users/registrations',
		as: :user_registration do
			get :cancel
		end
	end

	#Main Controllers
	resources :users
	resources :profiles
	resources :dashboard
	resources :workouts
    resources :exercises
    resources :activities

	#temporary while contructing pages.
	resources :not_implemented

resources :messages do
  member do
    post :new
  end
end
resources :conversations, only: [:index, :show, :new, :create] do
  member do
    post :reply
    post :trash
    post :untrash
    post :empty_trash
  end
 collection do
    get :trashbin
    get :empty_trash
 end
end

end

app/views/layouts/_ask_trainer.html.haml
- if user_signed_in?
  = button_to messages_path, method: :get, class: 'btn btn-default wt wt-ask-button' do
    %span.fa.fa-edit Ask a Question
- else
  %h2 Welcome!

app/views/layouts/_footer.html.haml
.row-clearfix
  .col-md-6
    - if user_signed_in?
      %strong= "Current Role: " + current_user.role
  .col-md-6
    %ul.list-inline.text-right
      %li= link_to 'About', not_implemented_index_path
      %li= link_to 'Feedback', not_implemented_index_path
      %li= link_to 'Legal', not_implemented_index_path
      %li= link_to 'Help', not_implemented_index_path

app/views/layouts/_form.html.haml
Reply:
\#{form_for [:reply, @conversation], url: reply_conversation_path(conversation) do |f|}
  = f.submit "Send Message", class: 'btn btn-primary'
  = submit_tag 'Clear Reply Box', type: :reset, class: 'btn btn-danger'

app/views/layouts/_loading.html.haml
%article.loading
  .progress.progress-striped.active
    .bar{:style => "width: 100%"}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.wt.navbar.navbar-default{:style => "margin:0 auto; height:70px"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to image_tag("placeholder_logo.gif", :border => 0), root_path, class: 'navbar-brand wt-logo'
    .collapse.navbar-collapse
      %ul.wt.nav.navbar-nav{:style => "margin-left:15px"}= render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  %li= button_to 'Dashboard', dashboard_index_path, method: :get, class: 'btn btn-default wt-nav-button'
  %li= button_to 'Workouts', workouts_path, method: :get, class: 'btn btn-default wt-nav-button'
  %li= button_to 'Messages', conversations_path, method: :get, class: 'btn btn-default wt-nav-button'
  %li= button_to 'Edit Profile', edit_user_registration_path, method: :get, class: 'btn btn-default wt-nav-button'
  %li= button_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'btn btn-default wt-nav-button'
  %li= button_to current_user.email, '#', method: :get, class: 'btn btn-default wt-nav-button'
  %li
    - if show_unread_count > 0
      = button_to messages_path, method: :get, class: 'btn btn-default wt-nav-button' do
        %i.fa.fa-envelope-o
          %strong= show_unread_count
- else
  %li= button_to 'Sign in', new_user_session_path, method: :get, class: 'btn btn-default wt-nav-button'

app/views/layouts/_sidebar.html.haml
= render 'layouts/ask_trainer'
%p
.wt.wt-sidebar-panel
  .collapse.navbar-collapse
    %ul.wt.nav.navbar-nav= render 'layouts/sidebar_links'

app/views/layouts/_sidebar_links.html.haml
- if user_signed_in?
  %li= link_to 'Exercises', exercises_path
  %li= link_to 'My Progress', not_implemented_index_path
- else
  %li= link_to 'Sign in', new_user_session_path
- if user_signed_in?
  - if current_user.admin?
    %li= link_to 'Users', users_path

app/views/layouts/application.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Workout Tracker"
    %meta{:content => content_for?(:description) ? yield(:description) : "Workout Tracker", :name => "description"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = yield(:head)
    = csrf_meta_tags
  %body{:class => "#{controller_name} #{action_name}"}
    .wt.wt-container
      .wt.wt-header
        = render 'layouts/navigation'
      .wt.wt-container-vbox
        .wt.wt-sidebar-hbox
          = render 'layouts/sidebar'
        .wt.wt-content-hbox{:role => "main"}
          = render 'layouts/messages'
          = yield
      .wt.wt-footer= render 'layouts/footer'